"""Cross-method SOTA comparison table (A1 vs trained baselines).

Aggregates A1's complete metrics (image + pixel, generated by
``evaluate_a1_complete_metrics.py``) with the baseline macro-means stored in
``outputs/unified/**/summary.csv``, and prints a per-dataset macro-mean table
with mean + std across all (seed, shot) combos.

Fairness notes encoded in the output:
  * A1 image score is max-pooling over the 448x448 anomaly map (matches the
    PatchCore / WinCLIP+ image-score convention); pixel metrics use stride=8.
  * A1 uses frozen DINO (dinov2_vitb14) + AnomalyCLIP features + a KNN normal
    memory bank (1/2/4-shot); it does NOT train on the target dataset.
  * Baselines use the same 1/2/4-shot normal references where available.
    AnomalyCLIP is zero-shot; ReMP-AD has 3 shot variants (no seeds) on MVTec;
    AdaptCLIP has 1-shot x 3 seeds on MVTec.
  * MPDD/BTAD baselines are legacy v2 DINO-only score caches and are NOT in the
    unified CSV, so only A1 is shown here for those datasets.
"""

from __future__ import annotations

import csv
import json
import statistics
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
UNIFIED_DIR = ROOT / "outputs" / "unified"
A1_ROOT = ROOT / "experiments" / "dynamic_fusion" / "v3_direction_a" / "a1_complete_metrics_20260819"
OUTPUT_DIR = ROOT / "outputs" / "logs"

SEEDS = [0, 1, 2]
SHOTS = [1, 2, 4]

# Metric key -> (a1 report section, a1 report key, unified csv column)
METRICS = {
    "image_auroc": ("image", "image_auroc", "image_auroc"),
    "image_ap": ("image", "image_ap", "image_ap"),
    "image_f1_max": ("image", "image_f1_max", "image_f1_max"),
    "pixel_auroc": ("pixel", "pixel_auroc", "pixel_auroc"),
    "pixel_ap": ("pixel", "pixel_ap", "pixel_ap"),
    "aupro": ("pixel", "pixel_aupro", "aupro"),
}

METHODS: dict[str, list[dict]] = {
    "mvtec": [
        {"name": "A1 (concat, ours)", "kind": "a1"},
        {"name": "PatchCore", "kind": "grid", "fmt": "patchcore_mvtec_seed_{seed}_shot_{shot}",
         "seeds": SEEDS, "shots": SHOTS},
        {"name": "WinCLIP+", "kind": "grid", "fmt": "winclip_mvtec_seed_{seed}_shot_{shot}",
         "seeds": SEEDS, "shots": SHOTS},
        {"name": "AnomalyDINO", "kind": "grid", "fmt": "anomalydino_mvtec_seed_{seed}_shot_{shot}",
         "seeds": SEEDS, "shots": SHOTS},
        {"name": "PromptAD", "kind": "grid", "fmt": "promptad_mvtec_seed_{seed}_shot_{shot}",
         "seeds": SEEDS, "shots": SHOTS},
        {"name": "AnomalyCLIP (zs)", "kind": "single", "fmt": "anomalyclip_mvtec_official"},
        {"name": "ReMP-AD", "kind": "shots", "fmt": "remp_ad_mvtec_k{shot}", "shots": SHOTS},
        {"name": "AdaptCLIP", "kind": "grid", "fmt": "adaptclip_mvtec_seed_{seed}_shot_{shot}",
         "seeds": SEEDS, "shots": [1]},
    ],
    "visa": [
        {"name": "A1 (concat, ours)", "kind": "a1"},
        {"name": "PatchCore", "kind": "grid", "fmt": "patchcore_visa_seed_{seed}_shot_{shot}",
         "seeds": SEEDS, "shots": SHOTS},
        {"name": "WinCLIP+", "kind": "grid", "fmt": "winclip_visa_seed_{seed}_shot_{shot}",
         "seeds": SEEDS, "shots": SHOTS},
        {"name": "AnomalyDINO", "kind": "grid", "fmt": "anomalydino_visa_seed_{seed}_shot_{shot}",
         "seeds": SEEDS, "shots": SHOTS},
        {"name": "PromptAD", "kind": "grid", "fmt": "promptad_visa_seed_{seed}_shot_{shot}",
         "seeds": SEEDS, "shots": SHOTS},
    ],
    "mpdd": [
        {"name": "A1 (concat, ours)", "kind": "a1"},
    ],
    "btad": [
        {"name": "A1 (concat, ours)", "kind": "a1"},
    ],
}

METRIC_LABELS = {
    "image_auroc": "I-AUROC",
    "image_ap": "I-AP",
    "image_f1_max": "I-F1",
    "pixel_auroc": "P-AUROC",
    "pixel_ap": "P-AP",
    "aupro": "AUPRO",
}


def a1_metric(dataset: str, seed: int, shot: int, metric: str) -> float | None:
    path = A1_ROOT / dataset / f"seed{seed}_k{shot}" / "metrics_report.json"
    if not path.is_file():
        return None
    report = json.loads(path.read_text(encoding="utf-8"))
    section, key, _ = METRICS[metric]
    return float(report["concat"]["mean"][section][key])


def baseline_metric(dirname: str, metric: str) -> float | None:
    path = UNIFIED_DIR / dirname / "summary.csv"
    if not path.is_file():
        return None
    with path.open(newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            if row["category"] == "macro_mean":
                return float(row[METRICS[metric][2]])
    return None


def combos_for(spec: dict) -> list[tuple[str, str]]:
    """Return [(combo_id, dirname)] for a non-A1 method."""
    kind = spec["kind"]
    if kind == "grid":
        out = []
        for seed in spec["seeds"]:
            for shot in spec["shots"]:
                dirname = spec["fmt"].format(seed=seed, shot=shot)
                out.append((f"s{seed}_k{shot}", dirname))
        return out
    if kind == "shots":
        return [(f"k{shot}", spec["fmt"].format(shot=shot)) for shot in spec["shots"]]
    if kind == "single":
        return [("zero_shot", spec["fmt"])]
    raise ValueError(f"unknown kind {kind}")


def collect(method_spec: dict, dataset: str, metric: str) -> list[float]:
    if method_spec["kind"] == "a1":
        vals = []
        for seed in SEEDS:
            for shot in SHOTS:
                v = a1_metric(dataset, seed, shot, metric)
                if v is not None:
                    vals.append(v)
        return vals
    vals = []
    for _, dirname in combos_for(method_spec):
        v = baseline_metric(dirname, metric)
        if v is not None:
            vals.append(v)
    return vals


def summarize(vals: list[float]) -> tuple[str, str, int]:
    n = len(vals)
    if n == 0:
        return "-", "-", 0
    mean = round(statistics.mean(vals), 4)
    std = round(statistics.stdev(vals), 4) if n >= 2 else "-"
    return f"{mean:.4f}", (f"{std:.4f}" if std != "-" else "-"), n


def main() -> None:
    rows: list[dict] = []
    for dataset, specs in METHODS.items():
        for spec in specs:
            row = {"dataset": dataset, "method": spec["name"]}
            for metric in METRICS:
                vals = collect(spec, dataset, metric)
                mean, std, n = summarize(vals)
                row[f"{metric}_mean"] = mean
                row[f"{metric}_std"] = std
            # n_combos is metric-independent; reuse aupro's count
            row["n_combos"] = len(collect(spec, dataset, "aupro"))
            rows.append(row)

    # Write CSV
    fieldnames = ["dataset", "method", "n_combos"]
    for metric in METRICS:
        fieldnames += [f"{metric}_mean", f"{metric}_std"]
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    csv_path = OUTPUT_DIR / "cross_method_sota_macro_mean.csv"
    with csv_path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    # Print per-dataset tables (headline metrics: I-AUROC, P-AUROC, P-AP, AUPRO)
    headline = ["image_auroc", "pixel_auroc", "pixel_ap", "aupro"]
    for dataset in METHODS:
        print(f"\n=== {dataset.upper()} macro mean (mean ± std, across seed/shot combos) ===")
        header = f"{'Method':<20}" + "".join(f"{METRIC_LABELS[m]:>16}" for m in headline) + f"{'N':>4}"
        print(header)
        print("-" * len(header))
        for row in rows:
            if row["dataset"] != dataset:
                continue
            cells = []
            for m in headline:
                mean = row[f"{m}_mean"]
                std = row[f"{m}_std"]
                if mean == "-":
                    cells.append(f"{'-':>16}")
                elif std == "-":
                    cells.append(f"{mean:>16}")
                else:
                    cells.append(f"{mean} ± {std}".rjust(16))
            print(f"{row['method']:<20}" + "".join(cells) + f"{row['n_combos']:>4}")

    print(f"\nWrote {csv_path}")


if __name__ == "__main__":
    main()
